### ISSUE TITLE
(WSL) venv issue? no extra index

### ISSUE THREAD

**Issue by BarfingLemurs** [BarfingLemurs/textgen#1]
python server.py                                                 Loading llama-7b-hf...                                                                                                  Loading checkpoint shards: 100%|████████████████████████████████████████████████████████| 33/33 [00:17<00:00,  1.85it/s]Traceback (most recent call last):                                                                                        File "/home/ubuntu/text-generation-webui/server.py", line 241, in <module>                                                shared.model, shared.tokenizer = load_model(shared.model_name)                                                        File "/home/ubuntu/text-generation-webui/modules/models.py", line 55, in load_model                                       model = model.cuda()                                                                                                  File "/home/ubuntu/text-generation-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 905, in cuda                                                                                                                         return self._apply(lambda t: t.cuda(device))                                                                          File "/home/ubuntu/text-generation-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply                                                                                                                       module._apply(fn)                                                                                                     File "/home/ubuntu/text-generation-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply                                                                                                                       module._apply(fn)                                                                                                     File "/home/ubuntu/text-generation-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 820, in _apply                                                                                                                       param_applied = fn(param)                                                                                             File "/home/ubuntu/text-generation-webui/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 905, in <lambda>                                                                                                                     return self._apply(lambda t: t.cuda(device))                                                                          File "/home/ubuntu/text-generation-webui/venv/lib/python3.10/site-packages/torch/cuda/__init__.py", line 247, in _lazy_init                                                                                                                       torch._C._cuda_init()                                                                                               RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

**Comment by BarfingLemurs** [comment]
pip install torch==1.13.1+cu117 torchaudio torchvision==0.14.1+cu117 --extra-index-url https://download.pytorch.org/whl/cu117                                                            Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu117                                     Collecting torch==1.13.1+cu117                                                                                            Downloading https://download.pytorch.org/whl/cu117/torch-1.13.1%2Bcu117-cp310-cp310-linux_x86_64.whl (1801.8 MB)           ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 GB 1.9 MB/s eta 0:00:00                                           Requirement already satisfied: torchaudio in ./venv/lib/python3.10/site-packages (2.0.1)                                Collecting torchvision==0.14.1+cu117                                                                                      Downloading https://download.pytorch.org/whl/cu117/torchvision-0.14.1%2Bcu117-cp310-cp310-linux_x86_64.whl (24.3 MB)       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.3/24.3 MB 12.3 MB/s eta 0:00:00                                        Requirement already satisfied: typing-extensions in ./venv/lib/python3.10/site-packages (from torch==1.13.1+cu117) (4.5.0)                                                                                                                      Requirement already satisfied: numpy in ./venv/lib/python3.10/site-packages (from torchvision==0.14.1+cu117) (1.24.2)   Requirement already satisfied: requests in ./venv/lib/python3.10/site-packages (from torchvision==0.14.1+cu117) (2.28.2)Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in ./venv/lib/python3.10/site-packages (from torchvision==0.14.1+cu117) (9.4.0)                                                                                                            Collecting torchaudio                                                                                                     Downloading https://download.pytorch.org/whl/cu117/torchaudio-2.0.1%2Bcu117-cp310-cp310-linux_x86_64.whl (4.4 MB)          ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.4/4.4 MB 13.5 MB/s eta 0:00:00                                            Downloading https://download.pytorch.org/whl/cu117/torchaudio-2.0.0%2Bcu117-cp310-cp310-linux_x86_64.whl (4.4 MB)          ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.4/4.4 MB 12.8 MB/s eta 0:00:00                                            Downloading https://download.pytorch.org/whl/cu117/torchaudio-0.13.1%2Bcu117-cp310-cp310-linux_x86_64.whl (4.2 MB)         ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 1.2 MB/s eta 0:00:00                                           Requirement already satisfied: urllib3<1.27,>=1.21.1 in ./venv/lib/python3.10/site-packages (from requests->torchvision==0.14.1+cu117) (1.26.15)                                                                                                Requirement already satisfied: charset-normalizer<4,>=2 in ./venv/lib/python3.10/site-packages (from requests->torchvision==0.14.1+cu117) (3.1.0)                                                                                               Requirement already satisfied: certifi>=2017.4.17 in ./venv/lib/python3.10/site-packages (from requests->torchvision==0.14.1+cu117) (2022.12.7)                                                                                                 Requirement already satisfied: idna<4,>=2.5 in ./venv/lib/python3.10/site-packages (from requests->torchvision==0.14.1+cu117) (3.4)                                                                                                             Installing collected packages: torch, torchvision, torchaudio                                                             Attempting uninstall: torch                                                                                               Found existing installation: torch 2.0.0                                                                                Uninstalling torch-2.0.0:                                                                                                 Successfully uninstalled torch-2.0.0                                                                                Attempting uninstall: torchvision                                                                                         Found existing installation: torchvision 0.15.1                                                                         Uninstalling torchvision-0.15.1:                                                                                          Successfully uninstalled torchvision-0.15.1                                                                         Attempting uninstall: torchaudio                                                                                          Found existing installation: torchaudio 2.0.1                                                                           Uninstalling torchaudio-2.0.1:                                                                                            Successfully uninstalled torchaudio-2.0.1                                                                         Successfully installed torch-1.13.1+cu117 torchaudio-0.13.1+cu117 torchvision-0.14.1+cu117
